  build-armv7:
    name: Build Linux ARMv7 (32-bit)
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Install cross compiler
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf
      - name: Build
        run: |
          make clean
          make wake-on-arp CC=arm-linux-gnueabihf-gcc
          mv wake-on-arp wake-on-arp-linux-armv7
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wake-on-arp-linux-armv7
          path: wake-on-arp-linux-armv7

name: Build and Release

on:
  push:
    branches: [ master ]

jobs:
  build-x64:
    name: Build Linux x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          make clean
          make wake-on-arp
          mv wake-on-arp wake-on-arp-linux-x64
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wake-on-arp-linux-x64
          path: wake-on-arp-linux-x64

  build-arm64:
    name: Build Linux ARM64
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          make clean
          make wake-on-arp
          mv wake-on-arp wake-on-arp-linux-arm64
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wake-on-arp-linux-arm64
          path: wake-on-arp-linux-arm64

  release:
    needs: [build-x64, build-arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Display artifacts
        run: ls -lR ./artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ github.run_id }}
          name: Nightly build ${{ github.run_id }}
          draft: false
          prerelease: true
          files: ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
